### PR TITLE
Id fix

### LINKED ISSUE #10: Data-Id doesn't remove reference to Dom elements
When a view is removed from the browser, it's references to Dom elements aren't cleaned up.

### PR DESCRIPTION
**Pull request by nicknisi**
Fix #10

references to dom elements are now cleaned up

### CODE REVIEW

File: thumbs.js [hunk 1]
```diff
@@ -122,12 +127,28 @@
...
+
         render: function render() {
             this._super('render', arguments);
             this.checkForIdentifiers();
             return this;
         },
 
+        remove: function () {
+            _.each(this.__identifiers, function (id) {
+                delete this[id],
```
Comment (doug-martin) [inline thumbs.js]: `delete` is not the most efficient way as it actually changes the hidden class you would be better off setting them all to `null`.

``` javascript
 this[id] = this['$' + id] = null;
```
